# Generated by Django 3.2.16 on 2022-10-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='finish_date',
            new_name='finish_vote_date',
        ),
        migrations.AddField(
            model_name='project',
            name='start_vote_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
