# Generated by Django 3.2.16 on 2022-10-28 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20221029_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 2, 3, 31, 626278)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 2, 3, 31, 626278)),
        ),
    ]
