# Generated by Django 3.2.16 on 2022-10-29 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20221029_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 3, 8, 51, 885775)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 3, 8, 51, 885775)),
        ),
    ]
