# Generated by Django 3.2.16 on 2022-10-29 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20221029_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfiles',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.product'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 3, 24, 5, 267302)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 3, 24, 5, 267302)),
        ),
    ]
