# Generated by Django 3.2.16 on 2022-10-29 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20221029_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 11, 14, 344847)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_vote_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 11, 14, 344847)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.product'),
        ),
    ]
