version: '3.7'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn apex.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/static
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
    ports:
      - 8000:8000
    networks:
      - server
    env_file:
      - ./.env.prod
    depends_on:
      - db
    container_name: backend

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - server
    env_file:
      - ./.env.prod.db
    container_name: db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - server
    volumes:
      - front-build:/frontend/build
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/

    container_name: frontend


volumes:
  postgres_data:
  static_volume:
  media_volume:
  front-build:

networks:
  server:
    driver: bridge